### ISSUE TITLE
mac 下不能用呢？

### ISSUE THREAD

**Issue by ceylog** [rossning92/movy#14]
➜ movy hello.js
env: node\r: No such file or directory

**Comment by Johnserf-Seed** [comment]
转义字符注意一下，没问题再link一下

**Comment by rossning92** [comment]
Thanks,  should be fixed by https://github.com/rossning92/movy/commit/98480577971a27897ef478b94d9e1263381a76ec

> npm i -g movy

to try again?

**Comment by ceylog** [comment]
@rossning92  可以了 谢谢大😄
