### ISSUE TITLE
Is it possible to add charts with animation

### ISSUE THREAD

**Issue by evenkiss** [rossning92/movy#17]
Hi Rossning92，

This is a great framework, I’m not sure if my idea can be realized, Is it possible to add charts with animation. 
I hope to get your advice or help.

Best Regards
Kevin

**Comment by rossning92** [comment]
Hey, @evenkiss, just added an example to create line chart animation. Please refer to `/examples/line-chart.js`.

![line-chart](https://user-images.githubusercontent.com/22453098/120248465-20d34b80-c22c-11eb-9d48-926faf15b1cc.gif)
