### ISSUE TITLE
没法跑

### ISSUE THREAD

**Issue by shanliangdeYWJ** [rossning92/movy#2]
按照文档操作，打开就是报错

控制台报了一个 BigInt的错误

**Comment by aybcoo** [comment]
我也是


> 按照文档操作，打开就是报错
> 
> 控制台报了一个 BigInt的错误

node 版本的问题，切换到高版本
我切到12.12 就可以了
你试一下

**Comment by rossning92** [comment]
#6 多谢，应该是版本问题。我把这个问题关闭了。
